module.exports = {
  NEXMO_VERIFY_ID : 'VERIFY_APP_KEY',
  NEXMO_VERIFY_SECRET :'NEXMO_VERIFY_SECRET',
  NEXMO_API_KEY: 'NEXMO_API_KEY',
  NEXMO_API_SECRET : 'NEXMO_API_SECRET',
  NEXMO_VOICE_SECRET :'NEXMO_VOICE_SECRET',
  NEXMO_VOICE_ID :'NEXMO_VOICE_ID',
  PRE_CONFIGURED_NUMBERS : ['YOUR_NUMBERS'],
  SERVER_PORT:'YOUR_PORT',
  SERVER_IP: 'YOUR SERVERIP'
};